version: '3.8'
services:
  postgres:
    container_name: pg
    image: postgres
    hostname: localhost
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  web:
    container_name: web
    image: nginx:latest
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "8080:80"
    working_dir: /code
    volumes:
      - ./:/code
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: php
    build:
      context: ./docker/php
    working_dir: /code
    depends_on:
      - postgres
    volumes:
      - ./:/code

volumes:
  postgres-data: